#服务启动端口
server :  
  port :  8087
  servlet-path: /JJF
spring:
  datasource:
        initialize: false
  redis:
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 1000
      min-idle: 5
    database: 0
    password: 123456
    host: 127.0.0.1
    port: 6379
  http:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
      file-size-threshold: 0
logging:
  level: info
